services:
  _defaults:
    autowire: true
    autoconfigure: true

  Hypergalaktisch\ParallaxBundle\:
    resource: '../src/*'
    exclude: '../src/{ContaoManager,DependencyInjection,Entity,Migrations,Tests,Kernel.php,HypergalaktischParallaxBundle.php}'

  Hypergalaktisch\ParallaxBundle\EventListener\HookListener:
    tags:
      - { name: contao.hook, hook: parseArticle, method: compileArticle }
      - { name: contao.hook, hook: parseTemplate, method: parseTemplate }
