services:
  _defaults:
    autowire: true
    autoconfigure: true

Hypergalaktisch\ContaoParallax\:
  resource: '../src/*'
  exclude: '../src/{ContaoManager,DependencyInjection,Entity,Migrations,Tests,Kernel.php, HypergalaktischContaoParallaxBundle.php}'

Hypergalaktisch\ParallaxBundle\EventListener\HookListener:
  tags:
    - { name: contao.hook, hook: parseArticle }